### ISSUE TITLE
Warning: peer dependencies not provided when using Yarn Modern

### ISSUE THREAD

**Issue by gabrielweyer** [angular-eslint/angular-eslint#1175] opened 2022-11-04 21:56 UTC
Apologies, there is no template for `@angular-eslint/schematics`. I'm using Yarn Modern and I'm trying to migrate to Angular 14. When running `yarn`, I get a handful of warnings:

```plaintext
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [65011] doesn't provide eslint (p7f3e9), requested by @angular-eslint/eslint-plugin
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [65011] doesn't provide eslint (p0df00), requested by @angular-eslint/eslint-plugin-template
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [65011] doesn't provide typescript (p5a8a4), requested by @angular-eslint/eslint-plugin
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [65011] doesn't provide typescript (pb87a6), requested by @angular-eslint/eslint-plugin-template
```

Example of a GitHub Action run with the warnings: https://github.com/gabrielweyer/pe-clr-viewer/actions/runs/3369164548/jobs/5588505715.

I can reproduce the issue by creating a new Angular 14 project, adding ESLint to it, and migrating to Yarn Modern:

```
> ng new my-app-yarn --package-manager yarn
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS
> yarn
No warnings
> ng add @angular-eslint/schematics
> yarn
No warnings
> npm install -g yarn
> yarn set version berry
> yarn
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [d30ee] doesn't provide eslint (p31ff7), requested by @angular-eslint/eslint-plugin
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [d30ee] doesn't provide eslint (p51c60), requested by @angular-eslint/eslint-plugin-template
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [d30ee] doesn't provide typescript (p4fe9c), requested by @angular-eslint/eslint-plugin
➤ YN0002: │ @angular-eslint/schematics@npm:14.1.2 [d30ee] doesn't provide typescript (p2bc44), requested by @angular-eslint/eslint-plugin-template
```

## Versions

| package | version |
| --- | --- |
| `@angular-eslint/schematics` | `^14.1.2` |
| `eslint` | `^8.26.0` |
| `Node` | `16.13.2` |

Output of `npx ng version`

```plaintext
Angular CLI: 14.2.7
Node: 16.13.2
Package Manager: yarn 3.1.1
OS: win32 x64

Angular: 14.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.7
@angular-devkit/build-angular   14.2.7
@angular-devkit/core            14.2.7
@angular-devkit/schematics      14.2.7
@angular/cli                    14.2.7
@schematics/angular             14.2.7
rxjs                            7.5.7
typescript                      4.8.4
```

My `package.json`:

```json
{
  "name": "pe-clr-viewer",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build-prod": "ng build --configuration production",
    "test": "ng test --browsers=Chrome --reporters=progress",
    "test-ci": "ng test --watch=false --reporters=progress,html --browsers=ChromeHeadlessNoSandbox --code-coverage",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.2.8",
    "@angular/common": "^14.2.8",
    "@angular/compiler": "^14.2.8",
    "@angular/core": "^14.2.8",
    "@angular/forms": "^14.2.8",
    "@angular/platform-browser": "^14.2.8",
    "@angular/platform-browser-dynamic": "^14.2.8",
    "@angular/router": "^14.2.8",
    "core-js": "^3.26.0",
    "rxjs": "^7.5.7",
    "tslib": "^2.4.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.7",
    "@angular-eslint/builder": "^14.1.2",
    "@angular-eslint/eslint-plugin": "^14.1.2",
    "@angular-eslint/eslint-plugin-template": "^14.1.2",
    "@angular-eslint/schematics": "^14.1.2",
    "@angular-eslint/template-parser": "^14.1.2",
    "@angular/cli": "14.2.7",
    "@angular/compiler-cli": "14.2.8",
    "@types/jasmine": "^4.3.0",
    "@types/node": "^18.11.8",
    "@typescript-eslint/eslint-plugin": "^5.42.0",
    "@typescript-eslint/parser": "^5.42.0",
    "eslint": "^8.26.0",
    "jasmine-core": "^4.5.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.4.1",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage": "^2.2.0",
    "karma-htmlfile-reporter": "^0.3.8",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "puppeteer": "^19.2.0",
    "ts-node": "^10.9.1",
    "typescript": "~4.8.4"
  },
  "packageManager": "yarn@3.1.1"
}
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment] 2022-11-17 13:18
I believe this is a duplicate of #1091

**Closed by JamesHenry** 2022-11-17 13:18 UTC
Labels: package: builder, triage
