### ISSUE TITLE
[@angular-eslint/prefer-standalone]: Cannot be disabled

### ISSUE THREAD

**Issue by phihochzwei** [angular-eslint/angular-eslint#2168] opened 2024-12-07 08:05 UTC
I try to disable this rule, since it simply breaks our project due to its removal of standalone: false. Unfortunately, I cannot disable for some reason Oo

```JSON
{
  "rules": {
   "@angular-eslint/prefer-standalone": [
					"off"
				]
  }
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/eslint-plugin`    | `19.0.1` |
| `@typescript-eslint/parser`        | `7.16.1` |
| `ESLint`                           | `8.57.0` |
| `node`                             | `22.6.0` |

```sh

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 19.0.4
Node: 22.6.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@angular/cdk                    19.0.2
@angular/cli                    19.0.4
@angular/google-maps            18.2.11
@angular/material               19.0.2
@angular/ssr                    19.0.4
@schematics/angular             19.0.4
ng-packagr                      19.0.1
rxjs                            7.5.7
typescript                      5.6.3
webpack                         5.97.1
zone.js                         0.15.0

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment] 2024-12-07 08:58
Please fork the stackblitz provided in the template to provide a reproduction: https://stackblitz.com/edit/angular-eslint-repros?file=eslint.config.js&view=editor

**Comment by phihochzwei** [comment] 2024-12-07 09:15
https://stackblitz.com/edit/angular-eslint-repros-6kynqhcw?file=eslint.config.js

**Comment by phihochzwei** [comment] 2024-12-07 09:19
I am not sure if that covers my case

**Comment by phihochzwei** [comment] 2024-12-07 09:23
Basically, I tried to disable it manually since the migration of our project failed  (see https://github.com/nrwl/nx/issues/29251) 

I somehow got the feeling that I am simply too stupid to disable it manually due the nesting of the .eslintrc-files throughout the project. However, my idea was, that, if I disable it in the root file, I should be propagated to all its descendants.

**Comment by JamesHenry** [comment] 2024-12-07 10:21
@phihochzwei Please check again, you haven't added the rule to the config at all

**Comment by JamesHenry** [comment] 2024-12-07 10:24
I have a strong suspicion that the issue does not belong on this repo and that you should instead provide full information over on the nx repo about what your eslintrc configs look like and what you are trying.

The most important thing is that you need to make sure you are applying the rule in the appropriate override (in eslintrc that is) so that the right specificity wins out

**Comment by ilyakonrad** [comment] 2024-12-09 09:28
I have the same issue.

>Components, Directives and Pipes should not opt out of standalone _eslint[@angular-eslint/prefer-standalone](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/docs/rules/prefer-standalone.md)_

Starting from Angular 19 `standalone` is the default setting, so all non-standalone components have got `standalone: false` from the CLI.

Neither of `"@angular-eslint/prefer-standalone": "off"` and `"@angular-eslint/prefer-standalone": ["off"]` works.

**Comment by JamesHenry** [comment] 2024-12-09 09:34
@ilyakonrad The ask remains the same, your comment is not a reproduction. It is essentially impossible for this to be an angular-eslint issue, because plugins do not control or influence ESLint's configuration mechanism, but if you can at least provide a reproduction we can start with that.

**Comment by ilyakonrad** [comment] 2024-12-09 10:02
Just found a solution. While updating `.eslintrc.json` (which I kept because of some ESLint issue) didn't work, updating of `eslint.config.mjs` did.

**Comment by Valentin-MF** [comment] 2024-12-09 14:30
I have an issue that might be related. I can't use the eslint-disable-next-line comment with the @angular-eslint/prefer-standalone rule.

I forked the stackblitz mentioned [here](https://github.com/angular-eslint/angular-eslint/issues/2168#issuecomment-2525040383):
https://stackblitz.com/edit/angular-eslint-repros-snng9szj?file=src%2Fmain.ts&view=editor

When I run `npm run lint` I have this output:
```
/home/projects/angular-eslint-repros-snng9szj/src/main.ts
   4:1  error    The component `standalone` property should be set to `true`  @angular-eslint/prefer-standalone
  12:3  warning  Unused eslint-disable directive (no problems were reported)
```

If you would prefer me to create another issue, please let me know.

**Comment by json-derulo** [comment] 2024-12-09 18:42
@Valentin-MF this is expected - the error is raised on the whole decorator, you can see this also in the [rule doc](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/docs/rules/prefer-standalone.md).

To silence the error, you have to place the comment before the decorator:

```ts
// eslint-disable-next-line -- This does not work. The lint error is not ignored.
@Component({
  selector: 'app-root',
  template: `
    <h1>Hello from {{ name }}!</h1>
    <a target="_blank" href="https://angular.dev/overview">
      Learn more about Angular
    </a>
  `,
  standalone: false,
})
export class AppComponent {}
```

**Comment by JamesHenry** [comment] 2024-12-10 07:40
Hmm damn, we should have changed that when true became the default and we started flagging specifically the usage of `standalone: false` being set...

Maybe let's fix it because it's still early in Angular 19, but yeah it will cause some minor irritation for folks who have already added some disable comments

**Comment by JamesHenry** [comment] 2024-12-10 07:54
https://github.com/angular-eslint/angular-eslint/pull/2172

**Comment by JamesHenry** [comment] 2024-12-10 08:07
@Valentin-MF Fixed and added before and after to the release notes https://github.com/angular-eslint/angular-eslint/releases/tag/v19.0.2

I'm going to go ahead and close this one as it is a configuration issue that seems to be related to Nx `.eslintrc.json` setups and any discussion should happen in https://github.com/nrwl/nx with clear reproductions/full config and directory structures.

Thanks all

**Closed by JamesHenry** 2024-12-10 08:07 UTC
Labels: awaiting response, package: eslint-plugin, triage

**Comment by Valentin-MF** [comment] 2024-12-10 08:13
@JamesHenry, Thank you so much for making the change so quickly.
