### ISSUE TITLE
Issues with rule validation of component- and directive-selector

### ISSUE THREAD

**Issue by lumaxis** [angular-eslint/angular-eslint#87] opened 2020-05-10 00:13 UTC
I have these rule configs in my `.eslintrc.json`:

```json
"@angular-eslint/directive-selector": [
  "error",
  {
    "type:": "attribute",
    "prefix": "gsh",
    "style": "camelCase"
  }
],
"@angular-eslint/component-selector": [
  "error",
  {
    "type:": "element",
    "prefix": "gsh",
    "style": "kebab-case"
  }
]
```

When I run `ng lint`, I get this error:

```
An unhandled exception occurred: --config:
        Configuration for rule "@angular-eslint/directive-selector" is invalid:
        Value {"type:":"attribute","prefix":"myapp","style":"camelCase"} should NOT have additional properties.
```

I tried various variations of my config and even compared to the validation in the rule definition but couldn't figure out what I'm doing wrong. Please help 😅 
https://github.com/angular-eslint/angular-eslint/blob/44392627ecd2e2cd332f1a9f47c0fec8dfaa5e59/packages/eslint-plugin/src/rules/component-selector.ts#L41-L66

**Comment by JamesHenry** [comment] 2020-07-21 06:39
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JamesHenry** [comment] 2020-08-18 18:38
Thanks again for the report @lumaxis - please can you provide a reproduction of this issue?

As you might have seen we have an integration-test which covers the use of these rules (in addition to the unit tests), so I think it is likely to be a configuration issue.

Something that jumped out at me was that your example error message does not actually match your example config (prefix is different). Could that be indicative of some mismatch in examples?

**Comment by JamesHenry** [comment] 2020-08-27 12:20
I'll close this for now, but if you are able to provide a reproduction please feel free to reopen and I'll take a look.

Many thanks!

**Closed by JamesHenry** 2020-08-27 12:20 UTC

**Comment by kdinev** [comment] 2020-12-16 11:11
@lumaxis @JamesHenry Had the same issue today, and it turns out it works if I remove the "type" from both directive and component selectors.

The following throws:
```json
"rules": {
  "@angular-eslint/directive-selector": [
    "error",
    {
      "type:": "attribute",
      "prefix": "bg",
      "style": "camelCase"
    }
  ],
  "@angular-eslint/component-selector": [
    "error",
    {
      "type:": "element",
      "prefix": "bg",
      "style": "kebab-case"
    }
  ]
}
```

> [error] Error: src-common\.eslintrc.json#overrides[0]:
	Configuration for rule "@angular-eslint/directive-selector" is invalid:
	Value {"type:":"attribute","prefix":"bg","style":"camelCase"} should NOT have additional properties.
    at ConfigValidator.validateRuleOptions (E:\GitHub\bellum-gens\node_modules\\@eslint\eslintrc\lib\shared\config-validator.js:142:23)

The following works:

```json
"rules": {
  "@angular-eslint/directive-selector": [
    "error",
    {
      "prefix": "bg",
      "style": "camelCase"
    }
  ],
  "@angular-eslint/component-selector": [
    "error",
    {
      "prefix": "bg",
      "style": "kebab-case"
    }
  ]
}
```

**Comment by EnricoVogt** [comment] 2021-01-21 14:06
@kdinev Thank you, I came across this problem today. Your solution works for me

**Comment by dinaNW** [comment] 2021-08-04 09:59
You've a typo in this line:
`"type:": "attribute",`

Remove the **:** after **type**.

**Comment by JamesHenry** [comment] 2021-08-04 10:08
Great spot @dinaNW! Looks like that was the issue all the way back to the very beginning of this thread
