### ISSUE TITLE
Elements with structural directive and bound properties output duplicate nodes

### ISSUE THREAD

**Issue by detljh** [angular-eslint/angular-eslint#336] opened 2021-02-11 23:54 UTC
Printing out the nodes for an element in a template with both structural directives and bound properties will output two nodes for the bound property.

```
code: `
      <div
        *ngIf="veryTrue$ | async"
        [disabled]="disabled$ | async"
      >
      </div>
      `,
```

```
create(context) {
  return {
    'Template BoundAttribute'(node: any) {
       console.log(node);
     },
  }
}
```

Outputs the below with two `BoundAttribute` nodes with `name="disabled$"`

```
<ref *2> BoundAttribute {
  name: 'ngIf',
  type: 'BoundAttribute',
  securityContext: 0,
  value: <ref *1> ASTWithSource {
    span: ParseSpan { start: 0, end: 17 },
    sourceSpan: AbsoluteSourceSpan { start: 27, end: 44 },
    ast: BindingPipe {
      span: [ParseSpan],
      sourceSpan: [AbsoluteSourceSpan],
      nameSpan: [AbsoluteSourceSpan],
      exp: [PropertyRead],
      name: 'async',
      args: [],
      type: 'BindingPipe',
      parent: [Circular *1]
    },
    source: 'veryTrue$ | async',
    location: '<input>@2:8',
    errors: [],
    type: 'ASTWithSource',
    parent: [Circular *2]
  },
  unit: null,
  sourceSpan: ParseSourceSpan {
    start: ParseLocation {
      file: [ParseSourceFile],
      offset: 20,
      line: 2,
      col: 8
    },
    end: ParseLocation {
      file: [ParseSourceFile],
      offset: 45,
      line: 2,
      col: 33
    },
    details: null
  },
  valueSpan: ParseSourceSpan {
    start: ParseLocation {
      file: [ParseSourceFile],
      offset: 27,
      line: 2,
      col: 15
    },
    end: ParseLocation {
      file: [ParseSourceFile],
      offset: 44,
      line: 2,
      col: 32
    },
    details: null
  },
  i18n: undefined,
  __originalType: 0,
  parent: Template {
    tagName: 'div',
    attributes: [],
    inputs: [ [BoundAttribute] ],
    outputs: [],
    templateAttrs: [ [Circular *2] ],
    children: [ [Element] ],
    references: [],
    variables: [],
    sourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    startSourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    endSourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    i18n: undefined,
    type: 'Template',
    parent: {
      type: 'Program',
      comments: [],
      tokens: [],
      range: [Array],
      loc: [Object],
      templateNodes: [Array],
      value: '\n' +
        '      <div\n' +
        '        *ngIf="veryTrue$ | async"\n' +
        '        [disabled]="disabled$ | async"\n' +
        '      >\n' +
        '      </div>\n' +
        '      ',
      parent: null
    }
  }
}
<ref *2> BoundAttribute {
  name: 'disabled',
  type: 'BoundAttribute',
  securityContext: 0,
  value: <ref *1> ASTWithSource {
    span: ParseSpan { start: 0, end: 17 },
    sourceSpan: AbsoluteSourceSpan { start: 66, end: 83 },
    ast: BindingPipe {
      span: [ParseSpan],
      sourceSpan: [AbsoluteSourceSpan],
      nameSpan: [AbsoluteSourceSpan],
      exp: [PropertyRead],
      name: 'async',
      args: [],
      type: 'BindingPipe',
      __originalType: 'BindingPipe',
      parent: [Circular *1]
    },
    source: 'disabled$ | async',
    location: '<input>@3:20',
    errors: [],
    type: 'ASTWithSource',
    __originalType: 'ASTWithSource',
    parent: [Circular *2]
  },
  unit: null,
  sourceSpan: ParseSourceSpan {
    start: ParseLocation {
      file: [ParseSourceFile],
      offset: 54,
      line: 3,
      col: 8
    },
    end: ParseLocation {
      file: [ParseSourceFile],
      offset: 84,
      line: 3,
      col: 38
    },
    details: null
  },
  valueSpan: ParseSourceSpan {
    start: ParseLocation {
      file: [ParseSourceFile],
      offset: 66,
      line: 3,
      col: 20
    },
    end: ParseLocation {
      file: [ParseSourceFile],
      offset: 83,
      line: 3,
      col: 37
    },
    details: null
  },
  i18n: undefined,
  __originalType: 'BoundAttribute',
  parent: Template {
    tagName: 'div',
    attributes: [],
    inputs: [ [Circular *2] ],
    outputs: [],
    templateAttrs: [ [BoundAttribute] ],
    children: [ [Element] ],
    references: [],
    variables: [],
    sourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    startSourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    endSourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    i18n: undefined,
    type: 'Template',
    parent: {
      type: 'Program',
      comments: [],
      tokens: [],
      range: [Array],
      loc: [Object],
      templateNodes: [Array],
      value: '\n' +
        '      <div\n' +
        '        *ngIf="veryTrue$ | async"\n' +
        '        [disabled]="disabled$ | async"\n' +
        '      >\n' +
        '      </div>\n' +
        '      ',
      parent: null
    }
  }
}
<ref *2> BoundAttribute {
  name: 'disabled',
  type: 'BoundAttribute',
  securityContext: 0,
  value: <ref *1> ASTWithSource {
    span: ParseSpan { start: 0, end: 17 },
    sourceSpan: AbsoluteSourceSpan { start: 66, end: 83 },
    ast: BindingPipe {
      span: [ParseSpan],
      sourceSpan: [AbsoluteSourceSpan],
      nameSpan: [AbsoluteSourceSpan],
      exp: [PropertyRead],
      name: 'async',
      args: [],
      type: 'BindingPipe',
      __originalType: 'BindingPipe',
      parent: [Circular *1]
    },
    source: 'disabled$ | async',
    location: '<input>@3:20',
    errors: [],
    type: 'ASTWithSource',
    __originalType: 'ASTWithSource',
    parent: [Circular *2]
  },
  unit: null,
  sourceSpan: ParseSourceSpan {
    start: ParseLocation {
      file: [ParseSourceFile],
      offset: 54,
      line: 3,
      col: 8
    },
    end: ParseLocation {
      file: [ParseSourceFile],
      offset: 84,
      line: 3,
      col: 38
    },
    details: null
  },
  valueSpan: ParseSourceSpan {
    start: ParseLocation {
      file: [ParseSourceFile],
      offset: 66,
      line: 3,
      col: 20
    },
    end: ParseLocation {
      file: [ParseSourceFile],
      offset: 83,
      line: 3,
      col: 37
    },
    details: null
  },
  i18n: undefined,
  __originalType: 'BoundAttribute',
  parent: Template {
    tagName: 'div',
    attributes: [],
    inputs: [ [Circular *2] ],
    outputs: [],
    templateAttrs: [ [BoundAttribute] ],
    children: [ [Element] ],
    references: [],
    variables: [],
    sourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    startSourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    endSourceSpan: ParseSourceSpan {
      start: [ParseLocation],
      end: [ParseLocation],
      details: null
    },
    i18n: undefined,
    type: 'Template',
    parent: {
      type: 'Program',
      comments: [],
      tokens: [],
      range: [Array],
      loc: [Object],
      templateNodes: [Array],
      value: '\n' +
        '      <div\n' +
        '        *ngIf="veryTrue$ | async"\n' +
        '        [disabled]="disabled$ | async"\n' +
        '      >\n' +
        '      </div>\n' +
        '      ',
      parent: null
    }
  }
}

```

**Comment by JamesHenry** [comment] 2021-02-12 01:18
Thanks @detljh, please report this on the angular repo as a compiler bug.

Here is what the raw AST from the angular compiler looks like (you can see the duplication of the disabled BoundAttribute)

![image](https://user-images.githubusercontent.com/900523/107719484-c2707480-6cf1-11eb-954c-b6e07d9d7a30.png)

**Comment by petebacondarwin** [comment] 2021-02-16 15:17
The duplicate bound attributes are by design and required in the generated code. This is very unlikely to change in the Angular compiler. So I would suggest that a workaround is added to this plugin instead.

**Comment by JamesHenry** [comment] 2021-02-16 15:23
Hi @petebacondarwin 👋  Hope you're keeping safe and well.

Thanks for letting us know, it should be straightforward enough to work around using a more advanced AST selector statement in any rules where this might apply.

@detljh I am going to close this given it applies more to knowing how to author future rules rather than an issue with existing rules (please correct me if I am wrong and open a new focused issue on the specific case)

**Closed by JamesHenry** 2021-02-16 15:23 UTC
Labels: blocked:@angular/compiler
