### ISSUE TITLE
[eqeqeq] suggestion changes imports in inline templates

### ISSUE THREAD

**Issue by json-derulo** [angular-eslint/angular-eslint#1473] opened 2023-08-10 20:06 UTC
**Description and reproduction of the issue**

In inline templates, the offered suggestion to fix the `eqeqeq` rule produces a wrong result and changes the imports to an invalid syntax. When the template is in a separate HTML file, everything seems to work fine.

```JSON
{
  "rules": {
    "@angular-eslint/template/eqeqeq": ["error"]
  }
}
```

```typescript
import { Component } from '@angular/core';

@Component({
  template: `
    <div *ngIf="value == null"></div>
  `
})
export class TestComponent {
  value?: string | null;
}
```

After applying the suggestion, the result is:

```typescript
import { Component } from= '@angular/core';

@Component({
  template: `
    <div *ngIf="value == null"></div>
  `
})
export class TestComponent {
  value?: string | null;
}
```

It seems like instead of the position of the start of the template, the position of the start of the file is taken into account.

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | 16.1.0` |
| `@angular-eslint/template-parser`         | `16.1.0` |
| `@typescript-eslint/parser`               | `5.62.0` |
| `ESLint`                                  | `8.46.0` |
| `node`                                    | `18.17.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 16.1.8
Node: 18.17.0
Package Manager: npm 9.6.7
OS: darwin x64

Angular: 16.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.1.8
@angular/cli                    16.1.8
@schematics/angular             16.1.8
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment] 2023-11-08 10:35
I think this is a duplicate of https://github.com/angular-eslint/angular-eslint/issues/538

**Closed by JamesHenry** 2023-11-08 10:35 UTC
Labels: package: eslint-plugin-template, triage
