### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@angular-devkit/architect'

### ISSUE THREAD

**Issue by Allsimon** [angular-eslint/angular-eslint#175] opened 2020-11-12 13:49 UTC
On my project (private, sorry I can't provide a reproduction), running `ng run myProject:lint` throws:

```
RUN ng run myProject:lint
 ---> Running in e909df3fab30
 An unhandled exception occurred: Cannot find module '@angular-devkit/architect'
Require stack:
- /app/node_modules/@angular-eslint/builder/dist/index.js
- /app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /app/node_modules/@angular/cli/models/architect-command.js
- /app/node_modules/@angular/cli/commands/run-impl.js
- /app/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /app/node_modules/@angular-devkit/schematics/tools/index.js
- /app/node_modules/@angular/cli/utilities/json-schema.js
- /app/node_modules/@angular/cli/models/command-runner.js
- /app/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-ok9I2N/angular-errors.log" for further details.
The command '/bin/sh -c ng run myProject:lint' returned a non-zero code: 127
```

my dev dependencies are:
```json
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1100.0",
    "@angular-eslint/builder": "0.6.0-beta.0",
    "@angular-eslint/eslint-plugin": "0.6.0-beta.0",
    "@angular-eslint/eslint-plugin-template": "0.6.0-beta.0",
    "@angular-eslint/schematics": "^0.6.0-beta.0",
    "@angular-eslint/template-parser": "0.6.0-beta.0",
    "@angular/cli": "^11.0.0",
    "@angular/compiler-cli": "^11.0.0",
    "@angular/language-service": "^11.0.0",
...
```

For some reasons upgrading Node (from `node:12.2.0` to `node:15.2.0`) seems to fix this problem :thinking:

**Comment by JamesHenry** [comment] 2020-11-13 22:35
I cannot reproduce this. Maybe your node_modules ended up in a bad state if `@angular-devkit/architect` cannot be found, because it should be brought in as part of the Angular CLI installation.

Maybe try nuking your node_modules (and maybe package/yarn.lock) and reinstalling.

I don't think there is anything we can do on the library side to help with this so closing for now.

**Closed by JamesHenry** 2020-11-13 22:35 UTC

**Comment by solkaz** [comment] 2021-04-07 13:20
@Allsimon I encountered this today, and noticed that while the Angular CLI does list `@angular-devkit/architect` as a dependency (as @JamesHenry correctly stated), it was located within `@angular/cli` folder (i.e. at `node_modules/@angular/cli/node_modules/@angular-devkit/architect`). I was able to solve this issue by running `npm dedupe`; this hoisted the dependency upwards (as other packages depend on it), so it was located at `node_modules/@angular-devkit/architect`.

**Comment by kaplan81** [comment] 2021-08-03 16:05
@solkaz the dedupe strategy works but it can create additional issues. In my case, as @Allsimon suggested, the solution had to do with upgrading Node to version 15.
