### ISSUE TITLE
lack of documentation for rules

### ISSUE THREAD

**Issue by JounQin** [angular-eslint/angular-eslint#503] opened 2021-05-24 06:21 UTC
**Description and reproduction of the issue**

As title, there are a lot of rules actually, but a few of the rules have their own documentation.

https://github.com/angular-eslint/angular-eslint/tree/master/packages/eslint-plugin/docs/rules
https://github.com/angular-eslint/angular-eslint/tree/master/packages/eslint-plugin-template/docs/rules

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `ESLint`                           | `X.Y.Z` |
| `node`                             | `X.Y.Z` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 12.0.0
Node: 12.22.1
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.1
... compiler, core

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0 (cli-only)
@angular-devkit/core         12.0.0 (cli-only)
@angular-devkit/schematics   12.0.0 (cli-only)
@schematics/angular          12.0.0 (cli-only)
rxjs                         7.0.1
typescript                   4.2.4
```

- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment] 2021-05-24 06:25
Duplicate of #197

**Comment by JamesHenry** [comment] 2021-05-24 06:26
PRs more than welcome!

**Closed by JamesHenry** 2021-05-24 06:25 UTC
Labels: package: eslint-plugin, triage
