### ISSUE TITLE
'noEslintrc' option has been declared with a 'no' prefix in the schema

### ISSUE THREAD

**Issue by samherrmann** [angular-eslint/angular-eslint#1069] opened 2022-06-24 21:56 UTC
When running the command `ng lint` after adding `@angular-eslint/schematics` to a new Angular CLI v14 project with the command `ng add @angular-eslint/schematics`, the follwoing warning is displayed in the console:

```sh
Warning: 'noEslintrc' option has been declared with a 'no' prefix in the schema.Please file an issue with the author of this package.
```

The Angular CLI displays this message for this package due to the following recent change:

https://github.com/angular/angular-cli/pull/23405/files#diff-2a058eb2b652edc5f9764c20613cf50955b198f8745fcf4d22be814a1b385594R237-R240

## Environment

```sh
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.3
Node: 16.13.2
Package Manager: npm 8.1.2 
OS: linux x64

Angular: 14.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.3
@angular-devkit/build-angular   14.0.3
@angular-devkit/core            14.0.3
@angular-devkit/schematics      14.0.3
@schematics/angular             14.0.3
rxjs                            7.5.5
typescript                      4.7.4
```

**Comment by mrlonis** [comment] 2022-06-27 18:40
Also getting this warning as well, but linting seems to work as expected

**Comment by Yrkki** [comment] 2022-07-01 13:42
Same here.

**Comment by truonghungit** [comment] 2022-07-01 21:45
Same issue

**Comment by damon-e-drake** [comment] 2022-07-04 03:48
I have the same as well with Angular 14.0.4, but linting seems to be working for me too.

**Comment by ajeurkar** [comment] 2022-07-05 08:21
I am getting the same warning message but the lining works.
`Warning: 'noEslintrc' option has been declared with a 'no' prefix in the schema.Please file an issue with the author of this package.`

**Comment by dvloper7** [comment] 2022-07-08 18:39
Install and be happy... or no ;)

npm i -D @nrwl/cli

**Comment by JamesHenry** [comment] 2022-07-09 09:53
Thanks folks, I also wish this wasn't the case. As @samherrmann noted in the original description this was added on the Angular CLI side and I currently have no way to suppress it.

I also cannot do a breaking change version until Angular next does, so renaming the option is not possible.

I have reached out to the Angular CLI team to ask them for a way to suppress this in the meantime

**Comment by JohannesHoppe** [comment] 2022-07-10 20:26
FYI, the root cause is tracked here: https://github.com/angular/angular-cli/issues/23397

**Comment by mrlonis** [comment] 2022-07-10 20:44
@JohannesHoppe thank you for sharing! Will track progress over there

**Comment by santosant** [comment] 2022-07-14 03:58
Great news! Thanks for reporting!

**Comment by JamesHenry** [comment] 2022-07-14 07:19
Angular CLI 14.0.6 was released and is the first version with the update in to not show the warning, so the resolution to this is to update to at least that version on the Angular CLI side.

There are no updates required for angular-eslint so closing this one but I’ll leave it pinned for a bit to aid with discoverability

**Closed by JamesHenry** 2022-07-14 07:19 UTC
