### ISSUE TITLE
eslint-disable does not work in Angular templates

### ISSUE THREAD

**Issue by LakMoore** [angular-eslint/angular-eslint#98] opened 2020-05-26 14:42 UTC
The following code in a template has no effect.
  

I can see where the disable directive is processed in es-lint and I don't think it can be re-used for templates.  I think this will need to be re-implemented in the parser in this project.  Any pointers, clues or ideas about where and how you want to achieve this?

**Comment by GerkinDev** [comment] 2020-08-18 18:22
The mentioned code is absent. But I guess, from the title, that this issue is related to #97

**Comment by JamesHenry** [comment] 2020-08-27 12:21
As @GerkinDev this report is currently incomplete, and probably best to handle as a duplicate of #97

**Closed by JamesHenry** 2020-08-27 12:21 UTC
