### ISSUE TITLE
@angular-eslint/no-output-on-prefix false positive

### ISSUE THREAD

**Issue by jlabaj** [angular-eslint/angular-eslint#663] opened 2021-09-02 14:11 UTC
Hello,

I have updated to angular 12.1.0 from 11 and suddenly I am getting this false positive from my eslint:
These are my versions of @angular-eslint:
"@angular-eslint/builder": "12.3.1",
"@angular-eslint/eslint-plugin": "12.3.1",
"@angular-eslint/eslint-plugin-template": "12.3.1",
"@angular-eslint/schematics": "12.3.1",
"@angular-eslint/template-parser": "12.3.1",

![image](https://user-images.githubusercontent.com/5179937/131855777-25238aa7-0d8f-4229-bf15-f3a99088c865.png)

But according to Angular coding style guide we can have even handler methods with on prefix:
![image](https://user-images.githubusercontent.com/5179937/131859166-1e8f7b1c-1ca4-4824-a4a2-30b9db21dcf3.png)

**Comment by rafaelss95** [comment] 2021-09-02 14:36
I couldn't reproduce it with 12.3.1. Would you mind to share your `.eslintrc.js(on)`?

In any case, you can find why this rule exists in https://angular.io/guide/styleguide#style-05-16.

**Comment by jlabaj** [comment] 2021-09-02 22:02
@rafaelss95 
as per: https://github.com/angular-eslint/angular-eslint
We strongly recommend that you do not try and hand-craft setups with angular-eslint and Nx. It is easy to get things wrong.

I should use only nx plugins:
https://nx.dev/latest/angular/guides/eslint

this is exactly my case

**Comment by JamesHenry** [comment] 2022-11-17 12:45
I'm going to close this one as a minimal repro was requested over a year ago here: https://github.com/nrwl/nx/issues/6931#issuecomment-924859623

Hopefully you managed to resolve the issue! 🙏

**Closed by JamesHenry** 2022-11-17 12:45 UTC
Labels: awaiting response, package: eslint-plugin
