### ISSUE TITLE
@angular-eslint/sort-ngmodule-metadata-arrays

### ISSUE THREAD

**Issue by ArtemFrontendACTUM** [angular-eslint/angular-eslint#890] opened 2022-02-05 18:37 UTC
Sorting auto-fix doesn't work.  Especially it's visible using multiple imports.
It tries to sort and even does sort something, but a major part of imports stays unsorted, and you have to run this fix like 10 times to make it finally sort everything right.

Versions:
```
"@angular-eslint/builder": "13.0.1",
"@angular-eslint/eslint-plugin": "13.0.1",
"@angular-eslint/eslint-plugin-template": "13.0.1",
"@angular-eslint/schematics": "13.0.1",
"@angular-eslint/template-parser": "13.0.1",
```

```json
// .eslintrc.json

{
  "root": false,
  "extends": [
    "./core.eslintrc.json",
    "./typescript.eslintrc.json"
  ],
  "overrides": [
    {
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "files": [
        "*.html"
      ],
      "parser": "@angular-eslint/template-parser",
      "plugins": [
        "@angular-eslint/template"
      ]
    },

    {
      "extends": [
        "plugin:@angular-eslint/recommended"
      ],
      "files": [
        "*.ts"
      ],
      "parser": "@typescript-eslint/parser",
      "plugins": [
        "@typescript-eslint",
        "@angular-eslint"
      ],
      "rules": {
        "@angular-eslint/component-max-inline-declarations": [
          "error",
          {
            "animations": 10,
            "template": 1,
            "styles": 1
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "style": "kebab-case"
          }
        ],
        "@angular-eslint/contextual-decorator": [
          "error"
        ],
        "@angular-eslint/contextual-lifecycle": [
          "error"
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "style": "camelCase"
          }
        ],
        "@angular-eslint/no-attribute-decorator": [
          "error"
        ],
        "@angular-eslint/no-conflicting-lifecycle": [
          "error"
        ],
        "@angular-eslint/no-empty-lifecycle-method": [
          "error"
        ],
        "@angular-eslint/no-host-metadata-property": [
          "error"
        ],
        "@angular-eslint/no-input-prefix": [
          "error"
        ],
        "@angular-eslint/no-input-rename": [
          "error"
        ],
        "@angular-eslint/no-inputs-metadata-property": [
          "error"
        ],
        "@angular-eslint/no-output-native": [
          "error"
        ],
        "@angular-eslint/no-output-on-prefix": [
          "error"
        ],
        "@angular-eslint/no-output-rename": [
          "error"
        ],
        "@angular-eslint/no-outputs-metadata-property": [
          "error"
        ],
        "@angular-eslint/no-pipe-impure": [
          "error"
        ],
        "@angular-eslint/no-queries-metadata-property": [
          "error"
        ],
        "@angular-eslint/prefer-on-push-component-change-detection": [
          "error"
        ],
        "@angular-eslint/relative-url-prefix": [
          "error"
        ],
        "@angular-eslint/sort-ngmodule-metadata-arrays": [
          "error"
        ],
        "@angular-eslint/use-component-selector": [
          "error"
        ],
        "@angular-eslint/use-component-view-encapsulation": [
          "error"
        ],
        "@angular-eslint/use-injectable-provided-in": [
          "error"
        ],
        "@angular-eslint/use-lifecycle-interface": [
          "error"
        ],
        "@angular-eslint/use-pipe-transform-interface": [
          "error"
        ],
        "@angular-eslint/prefer-output-readonly": [
          "error"
        ],
        "@angular-eslint/no-forward-ref": [
          "warn"
        ],
        "@angular-eslint/no-lifecycle-call": [
          "warn"
        ],
        "@angular-eslint/pipe-prefix": [
          "off"
        ]
      }
    }
  ]
}
```

**Comment by JamesHenry** [comment] 2022-11-24 11:02
Hi @ArtemFrontendACTUM this is a duplicate of #675 and will ultimately be addressed in #1232, please subscribe to #1232 for progress

**Closed by JamesHenry** 2022-11-24 11:02 UTC
