### ISSUE TITLE
@angular-eslint/use-pipe-transform-interface false positive

### ISSUE THREAD

**Issue by jlabaj** [angular-eslint/angular-eslint#662] opened 2021-09-02 13:38 UTC
Hello,

I have updated to angular 12.1.0 from 11 and suddenly I am getting this false positive from my eslint:
These are my versions of @angular-eslint:
"@angular-eslint/builder": "12.3.1",
    "@angular-eslint/eslint-plugin": "12.3.1",
    "@angular-eslint/eslint-plugin-template": "12.3.1",
    "@angular-eslint/schematics": "12.3.1",
    "@angular-eslint/template-parser": "12.3.1",

![image](https://user-images.githubusercontent.com/5179937/131853228-d9a8f3b0-435f-4f21-b8ed-6f59cacb4f7d.png)

**Comment by rafaelss95** [comment] 2021-09-02 14:29
Hi @jlabaj, I couldn't reproduce it with 12.3.1. Would you mind to share your `.eslintrc.js(on)`?

**Comment by jlabaj** [comment] 2021-09-02 15:03
@rafaelss95 sure:
{
    "root":true,
    "env":{
      "browser":true,
      "amd":true,
      "node":true
    },
    "globals":{
      "Blob":true,
      "document":true,
      "window":true,
      "Act":true,
      "Resources":true,
      "Marmind":true,
      "marmind":true,
      "Applications":true,
      "Collaboration":true,
      "console":true,
      "describe":true,
      "it":true,
      "expect":true,
      "inject":true,
      "beforeEach":true,
      "afterEach":true,
      "spyOn":true,
      "jasmine":true,
      "angular":true,
      "$":true,
      "_":true
    },
    "ignorePatterns": ["**/*.json"],
    "overrides":[
      {
        "files":[
          "*.js"
        ],
        "parser":"@typescript-eslint/parser",
        "parserOptions":{
          "ecmaVersion":2015,
          "sourceType":"module"
        },
        "extends":[
          "eslint:recommended"
        ],
        "rules":{
          "no-console":[
            "error",
            {
              "allow":[
                "warn",
                "error"
              ]
            }
          ]
        }
      },
      {
        "files":[
          "*.ts"
        ],
        "parser":"@typescript-eslint/parser",
        "parserOptions":{
          "project":"**/tsconfig.*?.json",
          "ecmaVersion":2020,
          "sourceType":"module"
        },
        "plugins":[
          "import",
          "@angular-eslint"
        ],
        "extends":[
          "eslint:recommended",
          "plugin:@typescript-eslint/eslint-recommended",
          "plugin:@typescript-eslint/recommended",
          "plugin:@angular-eslint/recommended"
        ],
        "rules":{
          "no-unreachable" :"error",
          "max-len": "off",
          "no-unused-vars": "off",
          "no-undef": "error",
          "@typescript-eslint/ban-ts-comment": "off",
          "@typescript-eslint/no-unused-vars":[
            "error",
            {
              "argsIgnorePattern":"^_"
            }
          ],
          "quotes":[
            "error",
            "single",
            {
              "allowTemplateLiterals":true
            }
          ],
          "@typescript-eslint/no-misused-promises":[
            "error"
          ],
          /*bug in this rule https://github.com/angular-eslint/angular-eslint/issues/662*/
           "@angular-eslint/use-pipe-transform-interface": "off",
          /*bug in this rule https://github.com/angular-eslint/angular-eslint/issues/663*/
           "@angular-eslint/no-output-on-prefix":"off"
        }
      }
    ]
}

and a second level eslintrc.json:
{
  "globals": {
    "Blob": true,
    "module": false,
    "document": true,
    "window": true,
    "Act": true,
    "Resources": true,
    "Marmind": true,
    "marmind": true,
    "Applications": true,
    "Collaboration": true,
    "console": true,
    "describe": true,
    "it": true,
    "expect": true,
    "inject": true,
    "beforeEach": true,
    "afterEach": true,
    "spyOn": true,
    "jasmine": true,
    "angular": true,
    "JQuery": true,
    "JQueryStatic": true,
    "$": true,
    "_": true
  },
  "overrides": [
    {
      "files": ["*.ts"],
      "parser": "@typescript-eslint/parser",
      "parserOptions": {
        "project": "**/tsconfig.*?.json",
        "ecmaVersion": 2020,
        "sourceType": "module"
      },
      "plugins": ["@nrwl/nx", "@nrwl/eslint-plugin-nx"],
      "rules": {
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "mar",
            "style": "camelCase"
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "mar",
            "style": "kebab-case"
          }
        ],
        "no-restricted-imports": [
          "error",
          {
            "paths": [
              {
                "name": "rxjs/Rx",
                "message": "Please import directly from 'rxjs' instead"
              }
            ]
          }
        ],
        "max-classes-per-file": "off",
        "@typescript-eslint/explicit-member-accessibility": "error",
        "@typescript-eslint/member-ordering": [
          "error",
          {
            "default": ["static-field", "instance-field", "static-method", "instance-method"]
          }
        ],
        "no-multiple-empty-lines": 2,
        "no-restricted-syntax": [
          "error",
          {
            "selector": "CallExpression[callee.object.name=\"console\"][callee.property.name=/^(log|debug|info|time|timeEnd|trace)$/]",
            "message": "Unexpected property on console object was called"
          }
        ],
        "@typescript-eslint/no-explicit-any": "error",
        "@typescript-eslint/explicit-module-boundary-types": "error",
        "no-empty": "error",
        "@typescript-eslint/no-inferrable-types": [
          "error",
          {
            "ignoreParameters": true
          }
        ],
        "eqeqeq": ["error", "smart"]
      }
    },
    {
      "files": ["*.component.html", "./apps/marmind-web/src/index.html"],
      "extends": ["plugin:@angular-eslint/template/recommended"],
      "rules": {}
    }
  ]
}

**Comment by rafaelss95** [comment] 2021-09-02 15:43
Please, in a next time, format JSON using the code snippet here, so it become readable 😄 

---

So, I've copied your configs to a test application and still can't reproduce, no reports at all...

<img width="447" alt="Test app" src="https://user-images.githubusercontent.com/11965907/131874707-ca1b0773-6911-47d8-b65f-f5ede7ff615f.png">

The best you can do now is to create a minimal reproduction of the problem in a repository, so I can take a look at this.

**Comment by jlabaj** [comment] 2021-09-02 17:58
@rafaelss95 yes sorry, didn't hit the format code in comment, corrected now. Ok hm I probably wont have time to do a minimum repro. I will try some more thing. Maybe I will get back to this later with a minimum repo.

**Comment by jlabaj** [comment] 2021-09-02 22:03
@rafaelss95
as per: https://github.com/angular-eslint/angular-eslint
We strongly recommend that you do not try and hand-craft setups with angular-eslint and Nx. It is easy to get things wrong.

I should use only nx plugins:
https://nx.dev/latest/angular/guides/eslint

this is exactly my case

**Comment by rafaelss95** [comment] 2021-09-17 21:28
@jlabaj in that case, can we close this and the other issue?

**Comment by GeorgeKnap** [comment] 2021-09-19 13:35
Just encountered this eslint error too in my project, please don't close it.
![image](https://user-images.githubusercontent.com/11920691/133929544-4f018e2d-7889-4ccb-a8a5-1d9b5a415196.png)

**Comment by rafaelss95** [comment] 2021-09-19 13:53
It's weird because, as I said some comments above, we have similar test cases that are passing on the latest version ([which is even documented in the auto-generated docs based on current tests](https://github.com/angular-eslint/angular-eslint/blob/83618221950bbb85ebe840407673c9ad3e15c6e3/packages/eslint-plugin/docs/rules/use-pipe-transform-interface.md)) + I tested it on a new project and I couldn't reproduce it... 

@GeorgeKnap btw, which versions of `@angular-eslint/*` packages do you have?

Note that as I also said above, if someone could provide a minimum repro I can take a look.

**Comment by GeorgeKnap** [comment] 2021-09-19 14:13
@rafaelss95 
![image](https://user-images.githubusercontent.com/11920691/133930738-1895c1b9-016a-42ad-a6ae-2413b2d088d0.png)

**Comment by gmiklich** [comment] 2021-10-04 19:30
I know you're looking for a minimal repro, but figured I'd chime in to say that I'm experiencing the same thing and am using angular eslint 12.5.0.

**Comment by rafaelss95** [comment] 2021-10-04 19:51
> I know you're looking for a minimal repro

Yes, could you help me to help you? 🥇 

I would be more than happy to check out any possible issues, but first I need to understand / see what issue you are facing.

**Comment by gmiklich** [comment] 2021-10-05 19:37
Yep, I wasn't sure if this would be closed due to "could not replicate", "lack of activity", etc., so I wanted to add a comment real quick that I was seeing the issue too.

[Here's a link](https://github.com/gmiklich/stackblitz-eslint-pipe-transform-test-hnu9mv) to what should be a public repo that illustrates the problem.  At least it shows the error in VSCode for me.

**Comment by JamesHenry** [comment] 2022-11-17 12:43
In v15 the minimum required version of ESLint will be bumped to 7.20.0 to formally close this issue

**Closed** 2022-11-20 12:41 UTC
Labels: BREAKING CHANGE, package: eslint-plugin
